title: IT Helpdesk

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  exclude:
    - README.md
include:
  - index.md
  - test.md
header_pages:
  - test.md

theme: minima