title: IT Helpdesk

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  exclude:
    - README.md
include:
  - pages/index.md
  - pages/apps/index.md
  - pages/apps/internet-browsers.md
  - pages/apps/winzip.md
header_pages:
  - pages/apps/index.md
author:
  name: Michael Grieco
  link: "https://michaelg29.github.io"
host_info:
  name: GitHub Pages
  link: "https://github.com/michaelg29/it-helpdesk"
  suggestion_link: "https://github.com/michaelg29/it-helpdesk/issues/new"

theme: minima